# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100, verbose_name='\u5185\u5bb9')),
                ('begintime', models.CharField(default='', max_length=20, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('done', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5b8c\u6210')),
                ('priority', models.IntegerField(default=0, verbose_name='\u4f18\u5148\u7ea7')),
                ('endtime', models.CharField(default='', max_length=20, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'db_table': 'todolist_item',
            },
        ),
    ]
